create extension if not exists pgcrypto;
create table public.commerciaux(id uuid primary key default gen_random_uuid(),nom text not null,actif boolean not null default true,created_at timestamptz not null default now());
create table public.offres(id uuid primary key default gen_random_uuid(),code text not null unique check(code in('ESSENTIEL','PRO','CHARLY_PLUS')),libelle text not null,prix_mensuel numeric(10,2) not null check(prix_mensuel>=0),actif boolean not null default true);
create table public.dossiers(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),commercial_id uuid not null references public.commerciaux(id),email_client text not null,offre_code text not null check(offre_code in('ESSENTIEL','PRO','AUTRE')),option_charly boolean not null default false,montant_autre numeric(10,2),montant_mensuel numeric(10,2) not null check(montant_mensuel>0),mois text not null check(mois ~ '^\d{4}-(0[1-9]|1[0-2])$'),commentaire text,doublon boolean not null default false);
create index dossiers_mois_idx on public.dossiers(mois);create index dossiers_email_mois_idx on public.dossiers(lower(email_client),mois);
create table public.challenges_mois(id uuid primary key default gen_random_uuid(),mois text not null unique check(mois ~ '^\d{4}-(0[1-9]|1[0-2])$'),paliers jsonb not null default '[]'::jsonb,prime_premier numeric(10,2) not null default 0,minimum_premier integer not null default 0,challenge_collectif_texte text,challenge_collectif_seuil integer,challenge_collectif_prime numeric(10,2));
create table public.admin_login_attempts(id bigint generated always as identity primary key,ip_hash text not null,created_at timestamptz not null default now());create index admin_attempts_idx on public.admin_login_attempts(ip_hash,created_at);
insert into public.offres(code,libelle,prix_mensuel) values('ESSENTIEL','Essentiel',29),('PRO','Pro',39),('CHARLY_PLUS','Option Charly+',10);
alter table public.commerciaux enable row level security;alter table public.offres enable row level security;alter table public.dossiers enable row level security;alter table public.challenges_mois enable row level security;alter table public.admin_login_attempts enable row level security;
create policy "public active commerciaux" on public.commerciaux for select to anon,authenticated using(actif=true);create policy "public active offres" on public.offres for select to anon,authenticated using(actif=true);create policy "public challenges" on public.challenges_mois for select to anon,authenticated using(true);
create or replace function public.classement_mois(p_mois text) returns table(commercial_id uuid,commercial text,dossiers bigint,mrr numeric,arr numeric,prime numeric,rang bigint) language sql security definer set search_path=public as $$
with stats as(select c.id commercial_id,c.nom commercial,count(d.id)::bigint dossiers,coalesce(sum(d.montant_mensuel),0)::numeric mrr from commerciaux c join dossiers d on d.commercial_id=c.id and d.mois=p_mois group by c.id,c.nom), ranked as(select *,dense_rank() over(order by dossiers desc,mrr desc,commercial asc)::bigint rang from stats), cfg as(select * from challenges_mois where mois=p_mois), team as(select coalesce(sum(dossiers),0) n from stats)
select r.commercial_id,r.commercial,r.dossiers,r.mrr,(r.mrr*12)::numeric arr,(coalesce((select max((p->>'prime')::numeric) from cfg,jsonb_array_elements(cfg.paliers)p where (p->>'seuil_dossiers')::int<=r.dossiers),0)+case when r.rang=1 and r.dossiers>=coalesce((select minimum_premier from cfg),0) then coalesce((select prime_premier from cfg),0) else 0 end+case when (select n from team)>=coalesce((select challenge_collectif_seuil from cfg),2147483647) then coalesce((select challenge_collectif_prime from cfg),0) else 0 end)::numeric prime,r.rang from ranked r order by r.rang,r.commercial;
$$;revoke all on function public.classement_mois(text) from public;grant execute on function public.classement_mois(text) to anon,authenticated;
